In [49]:
import numpy as np

In [50]:
range(10)

range(0, 10)

In [51]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
list(range(3, 10))

[3, 4, 5, 6, 7, 8, 9]

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(0.5, 10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [56]:
np.arange(0.5, 10.9)

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [57]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [58]:
np.arange(5,-4,-0.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [59]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [60]:
type(np.linspace(1,5,20))

numpy.ndarray

In [61]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [62]:
type(list(np.linspace(1,5,20)))

list

In [63]:
np.linspace(1,5,20, retstep= True)

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [64]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [65]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.zeros((3,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [67]:
np.ones((2, 5,9))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [70]:
np.ones((2, 5,9)).ndim

3

In [71]:
np.ones((2, 5,9)) + 5

array([[[6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6.]]])

In [72]:
np.ones((2, 5,9)) * 5

array([[[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]]])

In [73]:
np.ones((2, 5,9)) * 5*5

array([[[25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.]],

       [[25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25., 25., 25., 25., 25.]]])

In [75]:
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.86921822e-306, 1.89146896e-307, 7.56571288e-307]])

In [83]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
np.eye(4).ndim

2

In [84]:
a = np.eye(4)

In [85]:
a.shape

(4, 4)

In [86]:
a.size

16

In [87]:
a.ndim

2

In [93]:
a.reshape(8,-1)

array([[1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [94]:
a1 = np.random.randn(3,4)

In [95]:
a1

array([[-0.34170586,  0.11803084,  0.84319745,  0.25017108],
       [ 0.60886665, -1.81226792,  0.75512499,  0.43583349],
       [ 0.94225549,  0.60977009, -1.67870079,  0.35336977]])

In [96]:
import pandas as pd

In [97]:
pd.DataFrame(a1)

0         1         2         3
0 -0.341706  0.118031  0.843197  0.250171
1  0.608867 -1.812268  0.755125  0.435833
2  0.942255  0.609770 -1.678701  0.353370

In [98]:
a1

array([[-0.34170586,  0.11803084,  0.84319745,  0.25017108],
       [ 0.60886665, -1.81226792,  0.75512499,  0.43583349],
       [ 0.94225549,  0.60977009, -1.67870079,  0.35336977]])

In [100]:
a1[1][1]

-1.8122679187963364

In [103]:
a1[0:2, 0:2]

array([[-0.34170586,  0.11803084],
       [ 0.60886665, -1.81226792]])

In [104]:
a1[[0,1],0:2]

array([[-0.34170586,  0.11803084],
       [ 0.60886665, -1.81226792]])

In [106]:
a1[[0,1],0:2]

array([[-0.34170586,  0.11803084],
       [ 0.60886665, -1.81226792]])

In [107]:
a1

array([[-0.34170586,  0.11803084,  0.84319745,  0.25017108],
       [ 0.60886665, -1.81226792,  0.75512499,  0.43583349],
       [ 0.94225549,  0.60977009, -1.67870079,  0.35336977]])

In [109]:
a1[1:3,3:4]

array([[0.43583349],
       [0.35336977]])

In [110]:
a1[[1,2],3]

array([0.43583349, 0.35336977])

In [115]:
m1 = np.random.randint(1,3,(3,3))

In [116]:
m1

array([[1, 2, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [118]:
m2 = np.random.randint(2,4,(3,3))

In [119]:
m2

array([[3, 3, 3],
       [2, 2, 2],
       [3, 2, 3]])

In [120]:
m1*m2

array([[3, 6, 6],
       [2, 4, 2],
       [3, 2, 3]])

In [121]:
m1@m2

array([[13, 11, 13],
       [10,  9, 10],
       [ 8,  7,  8]])

In [122]:
m1

array([[1, 2, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [123]:
m2

array([[3, 3, 3],
       [2, 2, 2],
       [3, 2, 3]])

In [124]:
pow(m1,2)

array([[1, 4, 4],
       [1, 4, 1],
       [1, 1, 1]])

In [126]:
pow(m2,2)

array([[9, 9, 9],
       [4, 4, 4],
       [9, 4, 9]])

In [127]:
np.sqrt(m1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [128]:
np.log(m1)

array([[0.        , 0.69314718, 0.69314718],
       [0.        , 0.69314718, 0.        ],
       [0.        , 0.        , 0.        ]])

In [129]:
np.log10(m1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [130]:
np.exp(m1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [131]:
m1**2

array([[1, 4, 4],
       [1, 4, 1],
       [1, 1, 1]])

In [132]:
m1

array([[1, 2, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [133]:
pow(m1,4)

array([[ 1, 16, 16],
       [ 1, 16,  1],
       [ 1,  1,  1]], dtype=int32)

In [134]:
m1

array([[1, 2, 2],
       [1, 2, 1],
       [1, 1, 1]])