In [215]:
import numpy as np

In [216]:
l = [1,2,3,4,4]

In [217]:
type(l)

list

In [218]:
a = np.array(l)

In [219]:
type(a)

numpy.ndarray

In [220]:
a

array([1, 2, 3, 4, 4])

In [221]:
a1 = np.array([[1,2,3], [3,4,5]])

In [222]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [223]:
a2 = np.array([[[1,2,3], [4,0.5, 6]]])

In [224]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [225]:
a.ndim

1

In [226]:
a1.ndim

2

In [227]:
a2.ndim

3

In [228]:
a3 = np.array([[[1,2,3], [4,0.5, 6]],[[1,2,3], [4,0.5, 6]], [[1,2,3], [4,0.5, 6]]])

In [229]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [230]:
a3.ndim

3

In [231]:
l = [1,2,3,4]

In [232]:
a = np.asarray(l)

In [233]:
a

array([1, 2, 3, 4])

In [234]:
m = np.matrix(l)

In [235]:
m

matrix([[1, 2, 3, 4]])

In [236]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [237]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [238]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [239]:
### when list is passed asanyarray returns array
### when an array is passed asanyarray returns array
### when an matrix is passed asanyarray returns matrix

In [240]:
a

array([1, 2, 3, 4])

In [241]:
###  shallow copy
a1 = a

In [242]:
a

array([1, 2, 3, 4])

In [243]:
a1

array([1, 2, 3, 4])

In [244]:
a[0]

1

In [245]:
a[0] = 10

In [246]:
a

array([10,  2,  3,  4])

In [247]:
a1

array([10,  2,  3,  4])

In [248]:
a1

array([10,  2,  3,  4])

In [249]:
a1[3] = 50

In [250]:
a1

array([10,  2,  3, 50])

In [251]:
a

array([10,  2,  3, 50])

In [252]:
### deep copy
a2 = np.copy(a)

In [253]:
a2

array([10,  2,  3, 50])

In [254]:
a2[2] = 30

In [255]:
a2

array([10,  2, 30, 50])

In [256]:
a

array([10,  2,  3, 50])

In [257]:
### shallow copy : pointing to a same memory
### deep copy: pointing to a different memory

In [258]:
np.fromfunction(lambda i, j: i ==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [259]:
a = np.fromfunction(lambda i, j: i ==j, (4,4))

In [260]:
a.ndim

2

In [261]:
np.random.rand(2,3)

array([[0.73899883, 0.28940457, 0.6034268 ],
       [0.6355463 , 0.43015429, 0.29494617]])

In [262]:
### count of matrix, rows, columns
np.random.rand(2,3,2)

array([[[0.68426478, 0.04938158],
        [0.8974677 , 0.57605368],
        [0.06050418, 0.06476784]],

       [[0.59145325, 0.61163648],
        [0.56960515, 0.42406312],
        [0.14399839, 0.91147081]]])

In [263]:
np.random.rand(2,3,2,2)

array([[[[0.32394902, 0.26813919],
         [0.75546804, 0.09057143]],

        [[0.6177477 , 0.12045976],
         [0.24639246, 0.48341784]],

        [[0.9053684 , 0.55129765],
         [0.37069187, 0.08380722]]],


       [[[0.31979806, 0.91414301],
         [0.37942898, 0.68478076]],

        [[0.93902431, 0.1267261 ],
         [0.21685361, 0.76490165]],

        [[0.68619594, 0.02347619],
         [0.45424445, 0.16437196]]]])

In [264]:
np.random.rand(3,4,4)

array([[[0.42644483, 0.97948488, 0.51213007, 0.30644274],
        [0.67463303, 0.13167535, 0.88714823, 0.89978556],
        [0.68045003, 0.23171344, 0.17167233, 0.8985142 ],
        [0.08087173, 0.33419283, 0.4927866 , 0.19580593]],

       [[0.86000776, 0.79949547, 0.34671725, 0.94324517],
        [0.56187109, 0.86648531, 0.86270192, 0.9763755 ],
        [0.93543648, 0.78989408, 0.65224517, 0.15740723],
        [0.89721093, 0.11909807, 0.17756653, 0.16577782]],

       [[0.44567393, 0.95462393, 0.57003086, 0.29114871],
        [0.70948251, 0.76267833, 0.09023426, 0.02454129],
        [0.10108429, 0.99767377, 0.59586676, 0.01961279],
        [0.49151091, 0.32766005, 0.41002653, 0.95011635]]])

In [265]:
np.random.rand(3,4,5)

array([[[0.70479907, 0.2717649 , 0.95563524, 0.81851749, 0.86312367],
        [0.08882995, 0.41094004, 0.25189447, 0.81763156, 0.48870113],
        [0.422422  , 0.54688236, 0.01833741, 0.04025169, 0.46970132],
        [0.68298095, 0.67954398, 0.9984384 , 0.72123746, 0.20941089]],

       [[0.0209748 , 0.73021995, 0.72691659, 0.53480224, 0.64652793],
        [0.34024807, 0.20431915, 0.55281626, 0.18850633, 0.4610159 ],
        [0.309364  , 0.20208136, 0.8517431 , 0.70946768, 0.3474369 ],
        [0.89124287, 0.1290055 , 0.96689578, 0.93204328, 0.42246565]],

       [[0.19096935, 0.88971441, 0.51741409, 0.45632025, 0.48249057],
        [0.70917605, 0.89521732, 0.72054789, 0.69518111, 0.17704865],
        [0.91401748, 0.94279942, 0.51204283, 0.9064638 , 0.53348932],
        [0.55260305, 0.74262216, 0.79266081, 0.78077667, 0.02348898]]])

In [266]:

### standard normal distribution :  mean = 0 and standard deviation = 1
np.random.randn(3,4,4)

array([[[-0.70148065, -0.83608651,  0.10465253, -0.26015887],
        [-0.60719755, -0.58213988,  0.46212718, -0.45239954],
        [-0.09002044, -0.98344178,  0.0403343 ,  1.08267787],
        [-0.89587338, -0.1964684 ,  1.0449026 ,  0.47969862]],

       [[-0.63274595,  1.41803174,  2.7397482 ,  0.50048117],
        [ 2.69027744, -0.85146308,  0.59867378,  1.78181989],
        [-0.69878888,  0.31399351, -0.16183228,  1.71184832],
        [-1.76603442, -1.28218212,  0.09868977, -1.92714582]],

       [[ 0.36548708, -0.63927481,  1.05011621, -1.15664287],
        [-3.7061824 , -0.14621933,  0.7299958 ,  0.59910143],
        [-0.03745272, -1.82378135, -0.4912208 , -0.89583824],
        [-1.1553866 , -0.52619088,  2.34580342,  0.05276486]]])

In [267]:
np.random.randint(3,4,4)

array([3, 3, 3, 3])

In [268]:
np.random.randint(0,10,(4,4))

array([[2, 7, 0, 4],
       [8, 3, 0, 1],
       [8, 1, 7, 3],
       [7, 2, 5, 3]])

In [269]:
np.random.randint(0,10,(4,4,2))

array([[[7, 2],
        [8, 9],
        [2, 4],
        [7, 6]],

       [[0, 5],
        [6, 9],
        [4, 3],
        [8, 7]],

       [[0, 1],
        [4, 0],
        [5, 7],
        [1, 6]],

       [[6, 4],
        [1, 4],
        [8, 1],
        [1, 0]]])

In [270]:
np.random.randint(0,100,(4,4,2))

array([[[86, 80],
        [72, 46],
        [69, 46],
        [94, 10]],

       [[56, 14],
        [45, 28],
        [38, 18],
        [68, 66]],

       [[38, 68],
        [64, 24],
        [69, 69],
        [17, 41]],

       [[71,  3],
        [62, 96],
        [99, 72],
        [75, 56]]])

In [271]:
np.random.randn(3,4)

array([[ 1.27413432,  1.51310211,  0.72805155, -1.45635113],
       [ 0.69928738, -0.65526615, -0.04654884,  0.61688776],
       [ 0.08304441,  0.08736018, -1.22770651,  1.10260989]])

In [272]:
c = np.random.randn(3,4)

In [273]:
import pandas as pd

In [274]:
pd.DataFrame(c)

0         1         2         3
0  0.016498  0.385983 -0.084432  0.636605
1 -0.524424 -0.045407 -2.258664 -1.811177
2 -2.204873 -1.351585 -1.554720 -2.488022

In [275]:
c1 = np.random.randint(0,100,(4,4,2))

In [276]:
### 4*4*2 = 32
c1.reshape(4,8)

array([[84,  2, 76, 48, 29, 62, 72, 68],
       [42, 12, 13, 78, 53, 69,  5, 44],
       [55, 34, 94, 32, 53, 92, 64, 10],
       [26, 13,  5, 37, 46,  3, 34, 61]])

In [277]:

### negative number will changed internally into the required dimension if possible
c1.reshape(8,-1)

array([[84,  2, 76, 48],
       [29, 62, 72, 68],
       [42, 12, 13, 78],
       [53, 69,  5, 44],
       [55, 34, 94, 32],
       [53, 92, 64, 10],
       [26, 13,  5, 37],
       [46,  3, 34, 61]])

In [278]:
pd.DataFrame(c1.reshape(8,-1))

0   1   2   3
0  84   2  76  48
1  29  62  72  68
2  42  12  13  78
3  53  69   5  44
4  55  34  94  32
5  53  92  64  10
6  26  13   5  37
7  46   3  34  61

In [279]:
c = c1.reshape(16,-1)

In [280]:
pd.DataFrame(c)

0   1
0   84   2
1   76  48
2   29  62
3   72  68
4   42  12
5   13  78
6   53  69
7    5  44
8   55  34
9   94  32
10  53  92
11  64  10
12  26  13
13   5  37
14  46   3
15  34  61

In [281]:
c1.reshape(16,-1)

array([[84,  2],
       [76, 48],
       [29, 62],
       [72, 68],
       [42, 12],
       [13, 78],
       [53, 69],
       [ 5, 44],
       [55, 34],
       [94, 32],
       [53, 92],
       [64, 10],
       [26, 13],
       [ 5, 37],
       [46,  3],
       [34, 61]])